server:
  port: 8080

spring:
  application:
    name: make-your-profile-api
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: make_your_profile
      auto-index-creation: true

groq:
  api:
    key: ${GROQ_API_KEY}
    url: https://api.groq.com/openai/v1/chat/completions
    model: llama-3.3-70b-versatile

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
